### ISSUE TITLE
Fails to auto-resolve dependencies

### ISSUE THREAD

**Issue by tothsuo19** [vocobox/vocobox#2]
"Could not resolve dependencies for project org.vocobox:vocobox-api:jar:1.0.0-SNAPSHOT: Could not find artifact org.jzy3d:jzy3d-spectro:jar:0.9.2-SNAPSHOT at specified path C:\Users\Myself\Desktop\dev\vocobox\public\vocobox\dev\java\vocobox-api\lib\jzy3d-spectro.jar"

**Comment by vocobox** [comment]
Solved : I modified the pom
